version: "3.8"

services:
  user:
    build: ./user
    ports:
      - "3001:3001"
    env_file:
      - ./user/.env

  captain:
    build: ./captain
    ports:
      - "3002:3002"
    env_file:
      - ./captain/.env

  ride:
    build: ./ride
    ports:
      - "3003:3003"
    env_file:
      - ./ride/.env

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
